name: Continuous Integration Workflow

on: [push]

jobs:
    test:
        name: Run vitest tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v7
            
            - name: Set up pnpm
              uses: pnpm/setup@v1
              with:
                runtime: node@24
                cache: true
            
            - name: Run vitest tests
              run: pnpm test